// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaB_1BIWm934AEM18ecuM2vOYYczT3SIc',
    appId: '1:858189952746:android:e75c6e1845b165c9338993',
    messagingSenderId: '858189952746',
    projectId: 'test-drive-auth-51c24',
    storageBucket: 'test-drive-auth-51c24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu_OmRFZqEbLrmbjMoDHQBS8nBXvq9rzc',
    appId: '1:858189952746:ios:adb23240598af76c338993',
    messagingSenderId: '858189952746',
    projectId: 'test-drive-auth-51c24',
    storageBucket: 'test-drive-auth-51c24.appspot.com',
    iosClientId: '858189952746-nnb9krpfsl1rktmei95snrki8dvj5v49.apps.googleusercontent.com',
    iosBundleId: 'com.justiner.greengoals',
  );
}
